SELECT ID,EMAIL,PASSWORD,NAME,REGDATE FROM MEMBER;
INSERT INTO MEMBER(EMAIL,PASSWORD,NAME,REGDATE) VALUES ('test3@test4.co.kr', '2222', 'test2', '2020-09-30');


UPDATE MEMBER SET email WHERE id = ?

DELETE FROM MEMBER WHERE id = 10;